### PR TITLE
Qh sils permalink

### PR DESCRIPTION
**Pull request by qjhart**
This is the skeleton of  #30.

### CODE REVIEW

**Comment by qjhart** [comment]
@sbagg, this is the skeleton of the permalink setup.  I've added what I think is the best first pass at a structure, but right now it's not actaullyty getting any data.

**Comment by sbagg** [comment]
This is the updated theme page with sils-permalink added to it.

**Comment by jrmerz** [comment]
@sbagg I see a two issues.  first,  not sure what the `os` package is you installed in the app, nor do I see where you use it.  Additionally, you added the `request` package, which I don't see you use.  If you need a HTTP request library that works on both client and server, use `node-fetch`, if you are just on the client, use the browser native `fetch`

**Comment by sbagg** [comment]
I realized neither of those libraries are used.  I deleted them and pushed it back up.

**Pull request merged**
